name: Validation

on:
  pull_request:
  push:
    branches: [ development ]
    tags: [ '*' ]
  workflow_dispatch:

jobs:
  if: false
  validation:
    uses: JeffersonLab/clas12-validation/.github/workflows/ci.yml@main
